### ISSUE TITLE
Chat exhibits jumping glitch in Firefox

### ISSUE THREAD

**Issue by alembicq** [vyneer/orvods-go#38] opened 2024-11-03 02:26 UTC
When chat messages have been going for a few minutes, new messages cause the chat to glitch and jump a bit on new messages. I think this might be somehow related to old messages being removed and the scrollbar failing to adjust properly, but I'm not sure. It doesn't happen on Chrome, only on Firefox.

Here is a video showing the problem. This is on the latest Firefox Developer Edition, 133.0b3, with no extensions installed. (It happens on regular Firefox as well, but it was easier to record on this since it's a separate clean install.)

<https://files.catbox.moe/0oq6pc.mp4>

**Comment by vyneer** [comment] 2024-11-09 09:01
I noticed this happening in d.gg chat for me as well at some point in the past several months, so this must be some new Firefox issue/quirk. That being said, https://github.com/vyneer/orvods-go/commit/5d3105d2af94c7ec62430da784f57b2c7e10d0f9 seems to fix it for me. I've deployed the new build, try it out and let me know if it works for you as well.

**Comment by alembicq** [comment] 2024-11-09 14:55
Yep, it seems to be fixed on the currently deployed version. 👍

It's a shame that fixing it requires disabling scroll anchoring. But, at least in my opinion, making it more difficult to scroll up to click a link or read a message is less of an issue than constantly seeing new chat messages glitching.

**Comment by vyneer** [comment] 2024-11-09 15:25
Might be worth making a bug report on Bugzilla; I'll see if I can come up with a minimal example that doesn't rely on my website at some point when I have the time. I'll close the issue for now since the issue is solved, even if in a bit of a suboptimal fashion. Thank you for reporting the bug!

**Closed by vyneer** 2024-11-09 15:25 UTC

**Comment by alembicq** [comment] 2024-11-09 17:16
Sounds good. Thanks for the fix. :)
